export const catalogItems = [
  { label: 'newArrivals', href: '/catalog?category=new-arrivals' },
  { label: 'all', href: '/catalog' },
  { label: 'dress', href: '/catalog?category=dress' },
  { label: 'corsets', href: '/catalog?category=corsets' },
  { label: 'skirts', href: '/catalog?category=skirts' },
  { label: 'tops_blouses', href: '/catalog?category=tops-blouses' },
  { label: 'sleeves', href: '/catalog?category=sleeves' },
  { label: 'outerwear', href: '/catalog?category=outerwear' },
  { label: 'wedding_dresses', href: '/catalog?category=wedding-dresses' },
];

export const mockProducts = [
  {
    id: 1,
    name: 'Корсет из бархата',
    price: 21900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'corsets',
    isNew: true,
    badge: null,
  },
  {
    id: 2,
    name: 'Корсет new shine',
    price: 33900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'corsets',
    isNew: true,
    badge: 'hit',
  },
  {
    id: 3,
    name: 'Юбка корсетная',
    price: 23900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'skirts',
    isNew: false,
    badge: null,
  },
  {
    id: 4,
    name: 'Платье с рельефным низом',
    price: 38000,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'dress',
    isNew: true,
    badge: null,
  },
  {
    id: 5,
    name: 'Комплект пайетки',
    price: 30900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'dress',
    isNew: false,
    badge: null,
  },
  {
    id: 6,
    name: 'Корсет сетка серебристый',
    price: 27900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'corsets',
    isNew: false,
    badge: null,
  },
  {
    id: 7,
    name: 'Топ с длинными рукавами',
    price: 15900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'tops-blouses',
    isNew: true,
    badge: null,
  },
  {
    id: 8,
    name: 'Свадебное платье классик',
    price: 89900,
    currency: 'тг',
    image: '/placeholder.svg?height=500&width=400',
    category: 'wedding-dresses',
    isNew: false,
    badge: null,
  },
];
